<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '{attribute} cannot contain an email address' => '{attribute} не может содержать адрес электронной почты',
    '{attribute} cannot contain any spaces' => '{attribute} не может содержать пробелов',
    '{attribute} cannot contain the username' => '{attribute} не может содержать имени пользователей',
    '{attribute} must be a string' => '{attribute} должен быть строкой',
    '{attribute} should contain at least {n, plural, one{one character} other{# characters}} ({found} found)!' => '{attribute} должен содержать не мение {n, plural, one{одного символа} other{# символов}} ({found} найдено)!',
    '{attribute} should contain at least {n, plural, one{one lower case character} other{# lower case characters}} ({found} found)!' => '{attribute} должен содержать не мение {n, plural, one{одного символа в нижнем регистре} other{# символов в нижнем регистре}} ({found} найдено)!',
    '{attribute} should contain at least {n, plural, one{one numeric / digit character} other{# numeric / digit characters}} ({found} found)!' => '{attribute} должен содержать не мение {n, plural, one{одного числа} other{# чисел}} ({found} найдено)!',
    '{attribute} should contain at least {n, plural, one{one special character} other{# special characters}} ({found} found)!' => '{attribute} должен содержать не мение {n, plural, one{оного специального символа} other{# специальных символов}} ({found} найдено)!',
    '{attribute} should contain at least {n, plural, one{one upper case character} other{# upper case characters}} ({found} found)!' => '{attribute} должен содержать не мение {n, plural, one{одного символа в верхнем регистре} other{# символов в верхнем регистре}} ({found} найдено)!',
    '{attribute} should contain at most {n, plural, one{one character} other{# characters}} ({found} found)!' => '{attribute} должен содержать не более {n, plural, one{одного символа} other{# символов}} ({found} найдено)!',
    '{attribute} should contain exactly {n, plural, one{one character} other{# characters}} ({found} found)!' => '{attribute} должен содержать ровно {n, plural, one{однин символ} other{# символов}} ({found} найдено)!',
];
