<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access denied' => 'Доступ запрещен',
    'Can\'t delete uploaded file from API server: {info}' => 'Не удается удалить загруженный файл с сервера API: {info}',
    'Can\'t download one of file fragment from API server' => 'Невозможно загрузить один из фрагментов файла из сервера API.',
    'Can\'t finish upload file: {info}' => 'Не удалось завершить загрузку файла: {info}',
    'Can\'t get file list: {info}' => 'Не удается получить список файлов: {info}',
    'Can\'t get job status list' => 'Не удается получить список статусов служб',
    'Can\'t get job status list: {info}' => 'Не удается получить список статусов служб: {info}',
    'Can\'t read one of file fragment for upload' => 'Не удается прочитать один из фрагментов файла для загрузки',
    'Can\'t start downloading file from server API' => 'Не удается начать загрузку файла с сервера API',
    'Can\'t start file upload function' => 'Не удается запустить функцию загрузки файлов',
    'Can\'t upload chunk of file at number {chunk_num}: {info}' => 'Невозможно загрузить фрагмент файла по номеру {chunk_num}: {info}',
    'Can\'t upload file to the server' => 'Не удается загрузить файл на сервер',
    'Can\'t upload one of file fragment' => 'Не удается загрузить один из фрагментов файла',
    'Error' => 'Ошибка',
    'Error getting parameters' => 'Ошибка при получении параметров',
    'Error getting secret question' => 'Ошибка при получении секретного вопроса',
    'Error registration' => 'Ошибка регистрации',
    'Error send' => 'Ошибка отправки',
    'Error update' => 'Ошибка обновления',
    'File is not downloaded from API server' => 'Файл не загружается с сервера API',
    'File {filename} is not found in the directory for this user' => 'Файл \'{filename}\' не найден в каталоге этого пользователя',
    'Has no required params for  finish upload file' => 'Не получены обязательные параметры для завершения загрузки файла на сервер',
    'Has no required params for upload file' => 'Не получены обязательные параметры для загрузки файла с сервера',
    'Incorrect answer' => 'Неправильный ответ',
    'Incorrect code' => 'Неверный код',
    'Invalid request' => 'Неверный запрос',
    'No such file or directory' => 'Данный файл или каталог отсутствует',
    'Screen locked by another user\'s workflow!' => 'Экран заблокирован другим пользователем рабочего процесса',
    'Screen locked, confirmation required!' => 'Экран заблокирован, подтверждение обязательно',
    'Your browser sent a request that this server could not understand' => 'Ваш браузер отправил запрос, который этот сервер не смог понять',
];
