<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access denied. Couldn\'t release record for this screen' => 'Доступ запрещен, невозможно сделать релиз записи для этого экрана',
    'Couldn\'t create record, please try again in a few minutes' => 'Невозможно создать запись, пожалуйста попробуйте снова, через несколько минут',
    'Couldn\'t create record, screen is configured incorrectly' => 'Невозможно создать запись, экран настроен некорректно',
    'Couldn\'t delete record, screen is configured incorrectly' => 'Невозможно удалить запись, экран настроен некорректно',
    'Couldn\'t lock record, screen is configured incorrectly' => 'Невозможно заблокировать запись, экран настроен некорректно',
    'Couldn\'t lock workflow record, screen is configured incorrectly' => 'Невозможно заблокировать рабочий процесс записи, экран настроен некорректно',
    'Couldn\'t release record, screen is configured incorrectly' => 'Невозможно сделать релиз запии, экран настроен некорректно',
    'Couldn\'t unlock record, screen is configured incorrectly' => 'Невозможно разблокировать запись, экран настроен некорректно',
    'Couldn\'t unlock workflow record, screen is configured incorrectly' => 'Невозможно разаблокировать рабочий процесс записи, экран настроен некорректно',
    'Couldn\'t update record, please try again in a few minutes' => 'Невозможно обновить запись, пожалуйста попробуйте снова, через несколько минут',
    'Couldn\'t update record, screen is configured incorrectly' => 'Невозможно обновить запись, экран настроен некорректно',
    'Record can be updated' => 'Запись может быть обновлена',
    'Record is locked for updating' => 'Запись заблокирована для обновления',
    'Record is unlocked for update' => 'Запись разблокирована для обновления',
    'Screen has been locked at workflow' => 'Экран заблокирован в робочем процессе',
    'Screen has been released' => 'Сделан релиз экрана',
    'Screen has been unlocked at workflow' => 'Экран был раздлокирован в рабочем процессе',
    'The record was created successfully' => 'Запись создана успешно',
    'The record was deleted successfully' => 'Запись успешно удалена',
    'The record was updated successfully' => 'Запись успешно обновлена',
];
