<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access denied' => '',
    'Can\'t delete uploaded file from API server: {info}' => '',
    'Can\'t download one of file fragment from API server' => '',
    'Can\'t finish upload file: {info}' => '',
    'Can\'t get file list: {info}' => '',
    'Can\'t get job status list' => '',
    'Can\'t get job status list: {info}' => '',
    'Can\'t read one of file fragment for upload' => '',
    'Can\'t start downloading file from server API' => '',
    'Can\'t start file upload function' => '',
    'Can\'t upload chunk of file at number {chunk_num}: {info}' => '',
    'Can\'t upload file to the server' => '',
    'Can\'t upload one of file fragment' => '',
    'Error' => '',
    'Error getting parameters' => '',
    'Error getting secret question' => '',
    'Error registration' => '',
    'Error send' => '',
    'Error update' => '',
    'File is not downloaded from API server' => '',
    'File {filename} is not found in the directory for this user' => '',
    'Has no required params for  finish upload file' => '',
    'Has no required params for upload file' => '',
    'Incorrect answer' => '',
    'Incorrect code' => '',
    'Invalid request' => '',
    'No such file or directory' => '',
    'Screen locked by another user\'s workflow!' => '',
    'Screen locked, confirmation required!' => '',
    'Your browser sent a request that this server could not understand' => '',
];
