<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Couldn\'t lock record, screen is configured incorrectly' => 'Невозможно заблокировать запись, экран настроен неверно',
    'Couldn\'t unlock record, screen is configured incorrectly' => 'Невозможно разблокировать запись, экран настроен неверно',
    'Couldn\'t create record, please try again in a few minutes' => 'Не удалось создать запись, повторите попытку через несколько минут',
    'Couldn\'t create record, screen is configured incorrectly' => 'Не удалось создать запись, экран настроен неверно',
    'Couldn\'t delete record, screen is configured incorrectly' => 'Не удалось удалить запись, экран настроен неверно',
    'Couldn\'t update record, please try again in a few minutes' => 'Не удалось обновить запись, повторите попытку через несколько минут',
    'Couldn\'t update record, screen is configured incorrectly' => 'Не удалось обновить запись, экран настроен неверно',
    'Record can be updated' => 'Запись может быть обновлена',
    'Record is locked for updating' => 'Запись заблокирована для обновления',
    'Record is unlocked for update' => 'Запись разблокирована для обновления',
    'The record was created successfully' => 'Запись была успешно создана',
    'The record was deleted successfully' => 'Запись была успешно удалена',
    'The record was updated successfully' => 'Запись была успешно обновлена',
];
